production:
  adapter: postgresql
  encoding: unicode
  database: d13f3a99cjceic
  pool: 5
  username: lcixcopdpeqtsg
  password: d16vJ48I13VihY_E9DmiGR7giW

development:
  adapter: postgresql
  encoding: unicode
  database: uts-trace_development
  pool: 5
  username: haydenbleasel
  password:

test: &test
  adapter: postgresql
  encoding: unicode
  database: uts-trace_test
  pool: 5
  username: haydenbleasel
  password: